Make extensionless scripts runable in Windows
Previously, to make these run on Windows, I added the '.py'
extension. For example 'salt-master' => 'salt-master.py'

If this wasn't done, you would get an exception that looks like this
when spawning an addition process:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    File "C:\salt\bin\lib\multiprocessing\forking.py",
    line 380, in main
        prepare(preparation_data)
          File "C:\salt\bin\lib\multiprocessing\forking.py",
          line 489, in prepare
              file, path_name, etc = imp.find_module(main_name, dirs)
              ImportError: No module named salt-master

Instead of adding the '.py' extension, I found another work-around that
seems to avoid the issue. The details are described in the file comments.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>