Fix for "pip" detection so that setuptools is used
If setuptools is not used for PIP installs pip fails to install salt
with a rather nasty error:

error: option --single-version-externally-managed not recognized

from what I can dig up the simple use of:
    if "pip" in __file__

is sufficient to detect pip usage, and should be synonomous
with USE_SETUPTOOLS