Refresh mine.send documentation
Trying to use `salt '*' mine.send network.ip_addrs eth0` causes exception:

```
[ERROR   ] Function network.ip_addrs in mine.send failed to execute
[DEBUG   ] Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/modules/mine.py", line 255, in send
    **kwargs
  File "/usr/lib/python2.7/site-packages/salt/utils/functools.py", line 142, in call_function
    return salt_function(*function_args, **function_kwargs)
TypeError: ip_addrs() got multiple values for keyword argument 'interface'
```

Setting `interface` kwarg correctly sets mine data.

```
root@salt /srv/salt # salt '*' mine.send eth0_ip_addrs mine_function=network.ip_addrs eth0
salt.konrad.lab.trng.me:
    False
srv1.konrad.lab.trng.me:
    False
srv2.konrad.lab.trng.me:
    False
root@salt /srv/salt # salt '*' mine.send eth0_ip_addrs mine_function=network.ip_addrs interface=eth0
salt.konrad.lab.trng.me:
    True
srv1.konrad.lab.trng.me:
    True
srv2.konrad.lab.trng.me:
    True
```