Windows: Fix exception when certain grains are None
Certain grains may be set to `None` due to PR #37593. When either
the `manufacturer` or `productname` grain is `None` due to the cleaning
feature from the above referenced PR, an exception will be thrown that
looks like:

```
File "...\salt\grains\core.py", line 442, in _windows_virtual
  if 'QEMU' in osdata.get('manufacturer', ''):
TypeError: argument of type 'NoneType' is not iterable
```

Fix this by making `_windows_virtual` tolerant to grains that have
a value of `None`.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>