Pin major pyzmq version to be <22.0.0
```
  running build_ext
  running configure
  Using bundled libzmq
  already have bundled/zeromq
  already have platform.hpp
  checking for timer_create
  ************************************************
  ************************************************
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -c /root/setup-tests/temp-dir/timer_create5xgtbi9g.c -o build/temp.linux-x86_64-3.7/root/setup-tests/temp-dir/timer_create5xgtbi9g.o
  /root/setup-tests/temp-dir/timer_create5xgtbi9g.c: In function ‘main’:
  /root/setup-tests/temp-dir/timer_create5xgtbi9g.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
       timer_create();
       ^~~~~~~~~~~~
  gcc -pthread build/temp.linux-x86_64-3.7/root/setup-tests/temp-dir/timer_create5xgtbi9g.o -o build/temp.linux-x86_64-3.7/a.out
  build/temp.linux-x86_64-3.7/root/setup-tests/temp-dir/timer_create5xgtbi9g.o: In function `main':
  /root/setup-tests/temp-dir/timer_create5xgtbi9g.c:2: undefined reference to `timer_create'
  collect2: error: ld returned 1 exit status
  no timer_create, linking librt
  ************************************************
  building 'zmq.libzmq' extension
  creating build/temp.linux-x86_64-3.7/buildutils
  creating build/temp.linux-x86_64-3.7/bundled
  creating build/temp.linux-x86_64-3.7/bundled/zeromq
  creating build/temp.linux-x86_64-3.7/bundled/zeromq/src
  g++ -pthread -std=c++11 -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -DZMQ_IOTHREADS_USE_EPOLL=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/root/setup-tests/.venv/include -I/usr/include/python3.7m -c buildutils/initlibzmq.cpp -o build/temp.linux-x86_64-3.7/buildutils/initlibzmq.o
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyzmq
ERROR: Could not build wheels for pyzmq which use PEP 517 and cannot be installed directly
```