tagify: handle integer suffix list
The following code in fire_args can put at integer in the
suffix list:

    tag_suffix = [jid, 'args']

Therefore, fix tagify to convert the integer to a string,
in order to avoid the following error:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/salt/minion.py", line 1493, in _thread_return
    return_data = executor.execute()
  File "/usr/lib64/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/modules/saltutil.py", line 1437, in runner
    prefix='run'
  File "/usr/lib64/python2.7/site-packages/salt/utils/event.py", line 175, in fire_args
    tag = tagify(tag_suffix, prefix)
  File "/usr/lib64/python2.7/site-packages/salt/utils/event.py", line 203, in tagify
    return TAGPARTER.join([part for part in parts if part])
TypeError: sequence item 2: expected string, long found