Change zypperpkg to only parse stdout from rpm
If `rpm` on a system returns warnings on stderr, parsing would fail

```
...
    provide, realname = line.split("_|-")
ValueError: not enough values to unpack (expected 2, got 1)
```

and render related functions unusable.

Generally, query output to process should only be expected on stdout.
Hence, solve the issue and ensure functionality regardless of warnings
by discarding stderr.

Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>