doc: mock boto.regioninfo._load_json_file
Mockup _load_json_file() in order to avoid the following errors when
building the docs:

WARNING: autodoc: failed to import module 'salt.modules.boto_asg'; the following exception was raised:
Traceback (most recent call last):
  File "/public/src/salt/env/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/public/src/salt/salt/modules/boto_asg.py", line 63, in <module>
    import boto.ec2
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/ec2/__init__.py", line 31, in <module>
    RegionData = load_regions().get('ec2', {})
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/regioninfo.py", line 100, in load_regions
    endpoints = _load_builtin_endpoints()
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/regioninfo.py", line 128, in _load_builtin_endpoints
    resolver = BotoEndpointResolver(endpoints)
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/endpoints.py", line 150, in __init__
    endpoint_data, service_rename_map)
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/endpoints.py", line 44, in __init__
    super(_CompatEndpointResolver, self).__init__(endpoint_data)
  File "/public/src/salt/env/lib/python3.6/site-packages/boto/vendored/regions/regions.py", line 95, in __init__
    raise ValueError('Missing "partitions" in endpoint data')
ValueError: Missing "partitions" in endpoint data