We can't sort incomparable types in Py3 like integers and strings
```
Python 2.7.13 (default, Dec 21 2016, 07:16:46)
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> sorted({1: 2, 3: {4: 5}, '*OS': 'B'})
[1, 3, '*OS']
>>>
```
```
Python 3.5.3 (default, Jan 21 2017, 00:29:12)
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> sorted({1: 2, 3: {4: 5}, '*OS': 'B'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() < int()
>>>
```
We could also cast to strings any non string keys, however:
```
Python 3.5.3 (default, Jan 21 2017, 00:29:12)
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> sorted([str(k) for k in {1: 2, 3: {4: 5}, '*OS': 'B'}])
['*OS', '1', '3']
>>>
```
The order does not match the order on Py2.

Additionally, I see no justification as to why we need to sort these keys.
@vutny Any reason why we need the dictionary keys sorted?