Fix ValueError for template in AppsV1beta1DeploymentSpec
Instantiating AppsV1beta1DeploymentSpec without specifying a template
will raise:
ValueError: Invalid value for `template`, must not be `None`

Therefore directly specifying the template when instantiating
AppsV1beta1DeploymentSpec and use '' as default template. This fixes the
test_create_deployments test case (fixes #46329).

Signed-off-by: Benjamin Drung <benjamin.drung@profitbricks.com>