Fix ldap.managed errors
Regression from 6e4ce9d (#48666):
- AttributeError: 'tuple' object has no attribute 'encode'
- ValueError: too many values to unpack

Fixes: #52022.