Fix ldap.managed errors
Regression from 05e55bd (#48666):
- AttributeError: 'tuple' object has no attribute 'encode'
- ValueError: too many values to unpack

Fixes: #52022.