Drop enforcing new-style object for SaltYamlSafeLoader
Building the documentation with the Python 3 version of sphinx fails:

$ make -C doc html SPHINXBUILD=/usr/share/sphinx/scripts/python3/sphinx-build
/usr/share/sphinx/scripts/python3/sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
[autosummary] generating autosummary for: contents.rst, faq.rst,
glossary.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst,
ref/auth/all/salt.auth.django.rst, ref/auth/all/salt.auth.keystone.rst,
ref/auth/all/salt.auth.ldap.rst, ref/auth/all/salt.auth.mysql.rst,
ref/auth/all/salt.auth.pam.rst, ..., topics/using_salt.rst,
topics/utils/index.rst, topics/venafi/index.rst, topics/virt/disk.rst,
topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst,
topics/windows/windows-package-manager.rst,
topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst

Exception occurred:
  File "salt/utils/yamlloader.py", line 33, in <module>
    class SaltYamlSafeLoader(yaml.SafeLoader, object):
TypeError: metaclass conflict: the metaclass of a derived class must be
a (non-strict) subclass of the metaclasses of all its bases
The full traceback has been saved in /tmp/sphinx-err-hzfmdxlm.log, if
you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error
message can be provided next time.
A bug report can be filed in the tracker at
<https://github.com/sphinx-doc/sphinx/issues>. Thanks!

SaltYamlSafeLoader uses multiple inheritance to convert this object
into a new-style object. At least since pyyaml 3.11, yaml.SafeLoader is
already a new-style object. Therefore the multiple inheritance can be
dropped. This fixes #45684.