Get more test info
Currently we're getting an error message that looks like this:

    AssertionError: expected call not found.
    Expected: mock('fnord', 'fnordevice', 'fnordfs', ['-'],
                   config={'some': 'config'}, match_on='diamond')
    Actual: not called.

This is not at all what we want. It appears that something else is being
called, since vfstab is not. This *should* give us some more debugging
information to go on, since these tests all pass locally.