Prune obsolete code from integration test harness
These following are implemented by the SaltTesting modules:

SyndicCase
ShellCase
ShellCaseCommonTestsMixIn
SSHCase
SaltReturnAssertsMixIn

The class prototypes are still required, but the member functions are
obsolete and incorrect which can make troubleshooting a failure in the
test harness very confusing.

If the SaltTesting module is not installed, an error is raised when attempting
to start the integration tests:

ImportError: No module named salttesting