Update survey.py
Python3 requires UTF-8 encoding

Error:  
 File "/usr/local/lib/python3.6/site-packages/salt/runners/survey.py", line 174, in _get_pool_results
    digest = hashlib.sha256(str(minions[minion])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing