Don't include logging for passing tests.
The resulting XML file for integration tests is quite big:

```
ls -lah artifacts/xml-unittests-output/
 total 287M
 drwxr-xr-x 2 svc-build svc-build 4.0K Jul 26 15:57 .
 drwxr-xr-x 5 svc-build svc-build 4.0K Jul 26 12:44 ..
 -rw-r--r-- 1 svc-build svc-build  23M Jul 26 13:39 functional-test-results.xml
 -rw-r--r-- 1 svc-build svc-build 220M Jul 26 15:57 integration-test-results.xml
 -rw-r--r-- 1 svc-build svc-build  20M Jul 26 14:11 scenarios-test-results.xml
 -rw-r--r-- 1 svc-build svc-build  26M Jul 26 12:44 unit-test-results.xml
```

```
java.lang.OutOfMemoryError: Java heap space
 Caused: java.io.IOException: Remote call on EC2 (saltstack-ci) - kitchen-amd64 (i-0ca988d53c205223b) failed
 	at hudson.remoting.Channel.call(Channel.java:1004)
 	at hudson.FilePath.act(FilePath.java:1186)
 	at hudson.FilePath.act(FilePath.java:1175)
 	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:118)
 	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:159)
 	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:253)
 	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
 	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>