Fix AttributeError: module 'salt.config' has no attribute '_DFLT_LOG_FMT_JID'
```
$ python3 -m pytest -ra tests/pytests/integration/_logging/test_jid_logging.py
_______________________________ test_jid_in_logs _______________________________

    @PRE_PYTEST_SKIP
    def test_jid_in_logs(caplog, salt_call_cli):
        """
        Test JID in log_format
        """
>       jid_formatted_str = salt.config._DFLT_LOG_FMT_JID.split("%")[0]
E       AttributeError: module 'salt.config' has no attribute '_DFLT_LOG_FMT_JID'

tests/pytests/integration/_logging/test_jid_logging.py:15: AttributeError
```

Commit a973c357414b8116f1e15a0f8fb68b657b0a7a97 changed the private
variable to a public one.

Signed-off-by: Benjamin Drung <bdrung@debian.org>