Fix condition for ConfigTestCase.test_datetime_config_validation
The `jsonschema` library only uses `strict_rfc3339` and not `isodate`.
The test case `ConfigTestCase.test_datetime_config_validation` will fail
if `isodate` is available but not `strict_rfc3339`:

```
======================================================================
FAIL: test_datetime_config_validation (unit.utils.test_schema.ConfigTestCase)
[CPU:0.0%|MEM:26.0%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/utils/test_schema.py", line 897, in test_datetime_config_validation
    jsonschema.validate(
AssertionError: ValidationError not raised

----------------------------------------------------------------------
```

Therefore require `strict_rfc3339` to be present for running
`ConfigTestCase.test_datetime_config_validation`.

fixes #55936
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>