Only call remove() on a list when the item is present
The Python 3 tests were failing the `unit.states.test_linux_acl.LinuxAclTestCase.test_list_present`
test with the following stacktrace:

```
Traceback (most recent call last):
  File "/testing/tests/unit/states/test_linux_acl.py", line 237, in test_list_present
    ret = linux_acl.list_present(name, acl_type, acl_names, perms)
  File "/testing/salt/states/linux_acl.py", line 353, in list_present
    _current_acl_types.remove(_origin_owner)
ValueError: list.remove(x): x not in list
```

We need to check if the item is contained in the list before trying to remove it.