Fix for exception when exiting out of a runner
finally will be run even if self.exit() is called.

```
Traceback (most recent call last):
  File "/home/jacksontj/.virtualenvs/salt/bin/salt-run", line 10, in <module>
    execfile(__file__)
  File "/home/jacksontj/src/salt/scripts/salt-run", line 10, in <module>
    salt_run()
  File "/home/jacksontj/src/salt/salt/scripts.py", line 337, in salt_run
    client.run()
  File "/home/jacksontj/src/salt/salt/cli/run.py", line 47, in run
    if isinstance(ret, dict) and 'retcode' in ret:
UnboundLocalError: local variable 'ret' referenced before assignment
```