Allow libgit2 to guess sysdir homedir successfully
This prevents the generic error:

_pygit2.GitError: error loading known_hosts:

which is happening in certain pygit2/libgit2 versions