Fix UnboundLocalError in salt.scripts.salt_cloud
Importing salt.cloud inside the function causes the 'salt' name to be
treated as local. If the event of ImportError, the function will fail
with UnboundLocalError trying to get salt.defaults.exitcodes.EX_UNAVAILABLE:

(py2-env) salt-test@tommynaut:~> python
Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.scripts
>>> from mock import MagicMock, patch
>>>
>>> def die(*args):
...     raise ImportError
...
>>> mock = MagicMock(side_effect=die)
>>>
>>> with patch('__builtin__.__import__', mock):
...     salt.scripts.salt_cloud()
...
No handlers could be found for logger "salt.scripts"
salt-cloud is not available in this system
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/salt-test/salt/salt/scripts.py", line 447, in salt_cloud
    sys.exit(salt.defaults.exitcodes.EX_UNAVAILABLE)
UnboundLocalError: local variable 'salt' referenced before assignment

Declare the 'salt' name global to fix this.