Make binary data output possible
If for example a pillar contains binary data it's possible that it won't
be possible to print it when doing e.g pillar.items:

  File "/usr/lib/python3/dist-packages/salt/output/__init__.py", line 232, in strip_esc_sequence
    return txt.replace('\033', '?')
TypeError: a bytes-like object is required, not 'str'

Replace non-printable data during output with a message instead.