PY3: Fix broken minion
The following error occurs when the salt-minion runs using Python 3:
  File "...\bin\lib\site-packages\salt\minion.py", line 1880,
    in handle_event
      elif package.startswith('__schedule_return'):
      TypeError: startswith first arg must be bytes or a tuple of bytes,
      not str

Use `tag` instead of `package` when reading the tag names just like
every other case.

Broken by PR #36202.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>