Update carbon_return.py
Fix munin.run carbon return error:

2020-09-09 17:01:01,112 [salt.utils.schedule:853 ][ERROR   ][2099938] Unhandled exception running munin.run
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 844, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 299, in returner
    _send(saltdata, metric_base, opts)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 257, in _send
    sent_bytes = sock.send(data[total_sent_bytes:])
TypeError: a bytes-like object is required, not 'str'