The ``__init __`` process no longer needs to accept logging config (#61945)
* The ``__init __`` process no longer needs to accept logging config

Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>

* Could it be?!

```
07:08:22,973 [tornado.application:353 ][ERROR   ][MainProcess(2787)] [SaltMinion(id='minion')] Future <salt.ext.tornado.concurrent.Future object at 0x10
99108e0> exception was never retrieved: Traceback (most recent call last):
  File "/private/tmp/kitchen/testing/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/private/tmp/kitchen/testing/salt/minion.py", line 1772, in _handle_decoded_payload
    process = SignalHandlingProcess(
  File "/private/tmp/kitchen/testing/salt/utils/process.py", line 1068, in __new__
    instance._signal_handled = multiprocessing.Event()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 93, in Event
    return Event(ctx=self.get_context())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/synchronize.py", line 324, in __init__
    self._cond = ctx.Condition(ctx.Lock())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 78, in Condition
    return Condition(lock, ctx=self.get_context())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/synchronize.py", line 214, in __init__
    self._sleeping_count = ctx.Semaphore(0)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 83, in Semaphore
    return Semaphore(value, ctx=self.get_context())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/synchronize.py", line 126, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
```

https://github.com/saltstack/salt/commit/1d83b10025e3a3ad9ee7363abb91257e955a69ee

Signed-off-by: Pedro Algarvio <palgarvio@vmware.com>