Skip test_module_name_source_match if source directory is not found
Running the unittest with autopkgtest against the installed version of
salt fails:

```
======================================================================
FAIL: test_module_name_source_match
(unit.test_module_names.BadTestModuleNamesTestCase)
[CPU:0.0%|MEM:66.8%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/test_module_names.py", line 233, in
test_module_name_source_match
    assert not errors, _format_errors(errors)
AssertionError: The following 787 test module(s) could not be matched to
a source code file:

unit.test_minion (expected: salt/minion.py)
unit.test_version (expected: salt/version.py)
unit.test_transport (expected: salt/transport.py)
unit.test_template (expected: salt/template.py)
unit.test_state (expected: salt/state.py)
unit.test_spm (expected: salt/spm.py)
unit.test_pillar (expected: salt/pillar.py)
unit.test_payload (expected: salt/payload.py)
unit.test_master (expected: salt/master.py)
unit.test_log (expected: salt/log.py)
[...]
```

Therefore skip `test_module_name_source_match` if the source directory
`salt` is not found.

Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>