Fix tuned module on RHEL/CentOS 7.8
Tuneadm will - under certain circumstances - append a list of errors
found:

```
Available profiles:
- balanced                    - General non-specialized tuned profile
- desktop                     - Optimize for the desktop use-case
- hpc-compute                 - Optimize for HPC compute workloads
- latency-performance         - Optimize for deterministic performance at the cost of increased power consumption
- network-latency             - Optimize for deterministic performance at the cost of increased power consumption, focused on low latency network performance
- network-throughput          - Optimize for streaming network throughput, generally only necessary on older CPUs or 40G+ networks
- powersave                   - Optimize for low power consumption
- throughput-performance      - Broadly applicable tuning that provides excellent performance across a variety of common server workloads
- virtual-guest               - Optimize for running inside a virtual guest
- virtual-host                - Optimize for running KVM guests
Current active profile: virtual-guest

** COLLECTED WARNINGS **
No SMBIOS nor DMI entry point found, sorry.
** END OF WARNINGS **
```

This will confuse the cheap parser and result in the following error:

```
          ID: set_tuned_profile
    Function: tuned.profile
        Name: virtual-guest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/tuned.py", line 45, in profile
                  valid_profiles = __salt__["tuned.list"]()
                File "/usr/lib/python3.6/site-packages/salt/modules/tuned.py", line 64, in list_
                  result = [i.split("- ")[1].strip() for i in result]
                File "/usr/lib/python3.6/site-packages/salt/modules/tuned.py", line 64, in <listcomp>
                  result = [i.split("- ")[1].strip() for i in result]
              IndexError: list index out of range
```

This commit fixes the problem by cutting off any warnings.
A test was added for the specific situation as well.