states.pip: upgrade pip upgrade test versions
pip==6.0 causes the following stack trace on MacOS:
```py
ERROR: Traceback (most recent call last):
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/bin/pip", line 7, in <module>
    from pip import main
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/lib/python2.7/site-packages/pip/utils/__init__.py", line 22, in <module>
    from pip._vendor import pkg_resources, six
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 61, in load_module
    __import__(name)
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 71, in <module>
    __import__('pip._vendor.packaging.requirements')
  File "/private/tmp/salt-tests-tmpdir/6833-pip-upgrade-pip/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py", line 49, in <module>
    VERSION_PEP440 = Regex(Specifier._regex_str, re.VERBOSE | re.IGNORECASE)
AttributeError: type object 'Specifier' has no attribute '_regex_str'
```