Fix broken symlink in test_symlink_list
Running the unit tests on the release tarball fails on Linux:

```
======================================================================
FAIL: test_symlink_list (unit.fileserver.test_roots.RootsTest)
[CPU:0.0%|MEM:76.1%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/fileserver/test_roots.py", line 174, in test_symlink_list
    self.assertDictEqual(ret, {'dest_sym': 'source_sym'})
AssertionError: {} != {'dest_sym': 'source_sym'}
- {}
+ {'dest_sym': 'source_sym'}

----------------------------------------------------------------------
```

The file `tests/integration/files/file/base/dest_sym` is a symlink to
`source_sym` in the git repository, but it is a normal file in the release
tarball. Therefore just restore the symlink in that case.

Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>