yaml: Raise an exception when dumping unsupported types
Failure to represent an object is a bug so it should be noisy, not
quietly produce `NULL`.  The representer this commit disables was
added in commit 2e2ce5f1078b794eb87fe781d13b8af745c865d5.

Behavior before:

```pycon
>>> import salt.utils.yaml as y
>>> y.safe_dump(type("GeneratedObjectSubclass", (), {}))
'NULL\n'
```

Behavior after:

```pycon
>>> import salt.utils.yaml as y
>>> y.safe_dump(type("GeneratedObjectSubclass", (), {}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "salt/utils/yamldumper.py", line 270, in safe_dump
    return dump(data, stream, Dumper=SafeOrderedDumper, **kwargs)
  File "salt/utils/yamldumper.py", line 261, in dump
    return yaml.dump(data, stream, **kwargs)
  File "venv/lib/python3.8/site-packages/yaml/__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "venv/lib/python3.8/site-packages/yaml/__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "venv/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "venv/lib/python3.8/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "venv/lib/python3.8/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <class '__main__.GeneratedObjectSubclass'>)
```