Fix a type error in carbon returner
I was experimenting with munin.run and the carbon returner to send some metrics to my graphite instance using the salt minion's scheduler.

Got the following error:

2021-11-23 11:42:33,024 [salt.utils.schedule:875 ][ERROR   ][4032195] Unhandled exception running munin.run
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 866, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 297, in returner
    _send(saltdata, metric_base, opts)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 255, in _send
    sent_bytes = sock.send(data[total_sent_bytes:])
TypeError: a bytes-like object is required, not 'str'

This code was obviously written some time ago, and the migration to python3 causes it to misbehave.
Simply using encode on the string to be sent solves the problem.