Fix incorrect reactor target
The documentation has an incorrect reactor target

The current documentation will cause the following error
```
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'data'
```