Skip test_check_virtualname if source directory is not found
Running the unittest with autopkgtest against the installed version of
salt fails (log from salt 2019.2.3):

```
======================================================================
ERROR: test_check_virtualname (unit.test_virtualname.VirtualNameTestCase)
[CPU:0.0%|MEM:60.8%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.O28A17/autopkgtest_tmp/tests/unit/test_virtualname.py", line 89, in test_check_virtualname
    for entry in os.listdir(os.path.join(CODE_DIR, 'salt/')):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/autopkgtest.O28A17/autopkgtest_tmp/salt/'

----------------------------------------------------------------------
```

Therefore skip `test_check_virtualname` if the source directory `salt` is not
found.

Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>