Decode git call output in Python 3
The subprocess communicate() method returns byte streams for stdout and
stderr in Python 3. They need to be decoded to str. Otherwise the
version string parsing will fail:

Traceback (most recent call last):
  File "salt/version.py", line 522, in __discover_version
    return SaltStackVersion.parse(out)
  File "salt/version.py", line 267, in parse
    'Unable to parse version string: \'{0}\''.format(version_string)
ValueError: Unable to parse version string: 'b'c0e6782d''