Fixes to unit tests
Add skipIf pyvmomi is not installed

    NameError: global name 'vmodl' is not defined
    NameError: global name 'vim' is not defined

Fix skipIf typo for OpenBSD

    >>> import sys
    >>> sys.platform
    'openbsd6'

Avoid warning from glusterfs.py:

    Use specific 'len(elem)' or 'elem is not None' test

Enable boto_secgroup_test tests that work now:

    test skipped due to error in moto return - fixed in
    https://github.com/spulec/moto/commit/cc0166964371f7b5247a49d45637a8f936ccbe6f