Skip SSHPasswordTests if ssh binary is not found
If the ssh binary is not found in path, SSHPasswordTests will fail:

ERROR: test_password_failure (unit.ssh.test_ssh.SSHPasswordTests)
[CPU:0.0%|MEM:54.9%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/ssh/test_ssh.py", line 42, in test_password_failure
    client = ssh.SSH(opts)
  File "salt/client/ssh/__init__.py", line 226, in __init__
    raise salt.exceptions.SaltSystemExit('No ssh binary found in path -- ssh must be '
salt.exceptions.SaltSystemExit: None

Either SSHPasswordTests needs to be converted into a real unit test
(i.e. mocking the salt call) or this tests needs to be skipped if ssh is
not available.

Signed-off-by: Benjamin Drung <benjamin.drung@profitbricks.com>