[salt.cloud] master_minion_name referenced before assignment
Fixes error caused by 42ca06c9

[ERROR   ] There was a query error: local variable 'master_minion_name' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 389, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1611, in run_map
    if name in (master_name, master_minion_name):
UnboundLocalError: local variable 'master_minion_name' referenced before assignment