salt/states/boto_route53.py: fix parsing the deets dictionary
In case of private hosted zones, the validation fails because the
data format is incompatible with the parsing code.

Example:
deets: {u'VPCs': [{u'VPCId': u'vpc-f2e7c094', u'VPCRegion':
u'eu-west-1'}], u'HostedZone': {u'ResourceRecord SetCount': u'2',
u'CallerReference': u'0beecc60-279a-4981-878d-663d3228c042', u'Config':
{u'PrivateZone': u'true'}, u'Id': u'/hostedzone/Z1ANNYV58T6IGH',
u'Name': u'foo.bar.'}}

Parsing the example without this patch results in:
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in
call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in
wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/boto_route53.py",
line 442, in hosted_zone_present
    for v, d in deets.get('VPCs', {}).items():
AttributeError: 'ListElement' object has no attribute 'items'