Be more helpful when missing arguments.
BEFORE:
```
(code-salt)salt:~/code/salt # salt salt test.echo
salt:
    Traceback (most recent call last):
      File "/root/code/salt/salt/minion.py", line 411, in _thread_return
        ret['return'] = func(*args, **kwargs)
    TypeError: echo() takes exactly 1 argument (0 given)
```

AFTER:
```
(code-salt)salt:~/code/salt # salt salt test.echo
salt:
    Missing arguments executing "test.echo": ArgSpec(args=['text'], varargs=None, keywords=None, defaults=None)
```