Fix the case both DNS count and order changes in Windows
In case both number of DNS servers and their order
changes, while checking for the order, we will get
IndexError: list index out of range