Skip ExtendTestCase if templates directory is missing
The release tarball does not contain the `templates` directory.
Therefore `ExtendTestCase` will fail:

```
======================================================================
ERROR: test_run (unit.utils.test_extend.ExtendTestCase)
[CPU:0.0%|MEM:53.9%]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/utils/test_extend.py", line 40, in test_run
    out = salt.utils.extend.run('test', 'test', 'this description', integration.CODE_DIR, False)
  File "salt/utils/extend.py", line 242, in run
    MODULE_OPTIONS = _fetch_templates(os.path.join(salt_dir, 'templates'))
  File "salt/utils/extend.py", line 76, in _fetch_templates
    for item in os.listdir(src):
FileNotFoundError: [Errno 2] No such file or directory: ' templates'
```

Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>