Fix ssh client TypeError
salt-ssh -i '*' test.ping
...
File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 1129, in cmd_block
File "/home/ezh/.virtualenvs/salt/lib/python3.4/site-packages/salt/client/ssh/__init__.py", line 1084, in shim_cmd
File "/home/ezh/.virtualenvs/salt/lib64/python3.4/tempfile.py", line 417, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface