Fix unreachable ssh-id-wrapper template when root_dir is relative
Since the git commands will be executed from the user home directory, if
salt root_dir is set to a relative path (for example using
`root_dir: ./.tmp/` in salt config), then the git/ssh-id-wrapper
template may be unreachable and we may encouter the following error that
this patch is fixing:

```
[ERROR   ] Command '[u'git', u'ls-remote', u'git@github.com:bbinet/salt-formula-linux.git']' failed with return code: 128
[ERROR   ] stderr: error: cannot run .tmp/thin/py2/salt/templates/git/ssh-id-wrapper: No such file or directory
fatal: unable to fork
[ERROR   ] retcode: 128
[ERROR   ] Failed to check remote refs: Unable to authenticate using identity file:

error: cannot run .tmp/thin/py2/salt/templates/git/ssh-id-wrapper: No such file or directory
fatal: unable to fork
```