Disambiguate str vs tuple containment check
If for an unrelated reason the `os` grain is `None`, an interesting, and
very likely error happens here:
```python
16:26:17.769 [salt.loader.lazy ]:1150 [    8] [ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.xbpspkg. Module will not be loaded: 'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1133, in _process_virtual
    virtual = self.run(virtual_attr)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/xbpspkg.py", line 32, in __virtual__
    if __grains__["os"] in ("Void") and _check_xbps():
TypeError: 'in <string>' requires string as left operand, not NoneType
```